version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "📦 deps: "
    reviewers:
      - "akcelero"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "📦 deps: "
    reviewers:
      - "akcelero"
    groups:
      uv:
        patterns:
          - "*"
